#!/usr/bin/env bash

if [[ $1 == "--help" || $1 == "-h" ]]; then
  echo "usage: use \`run\` to run all scripts in runs/common and runs/<os> (macos or wsl)"
  echo "       use \`run <filter-query>\` to only run scripts whose name contains the given string"
  echo "       use \`run dry <filter-query>\` to dry run the installation"
  exit 0
fi

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
filter=""
dry="0"

while [[ $# -gt 0 ]]; do
  if  [[ $1 == "dry" ]]; then
    dry="1"
  else
    filter="$1"
  fi
  shift

done

log() {
  if [[ $dry == "1" ]]; then
    echo "[DRY_RUN]: $@"
  else
    echo "$@"
  fi
}

execute() {
  log "execute $@"
  if [[ $dry == "1" ]]; then
    return
  fi

  "$@" # execute the passed command
}

cd "$script_dir"
source ./lib/os.sh
source ./lib/helpers.sh

if [[ $OS == "unsupported" ]]; then
  echo "Unsupported platform (need macOS or WSL)"
  exit 1
fi

log "$script_dir -- os: $OS -- filter: $filter"

# common runs first (sorts before macos and wsl)
folders="./runs/common ./runs/$OS"

scripts=$(find_scripts $folders)

# Likely forgot to make executable
non_scripts=$(find_non_scripts $folders)
if [[ $non_scripts != "" ]]; then
  log "ATTENTION: you have non executable files:"
  log "$non_scripts"
  log "Aborting execution"
  exit 1
fi

for script in $scripts; do
  if [[ $(basename $script) != *"$filter"* ]]; then
    log "ignoring $script"
    continue
  fi

  execute $script || exit 1
done
